name: Go Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
        check-latest: true

    - name: Get dependencies
      run: go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Run tests with coverage
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        fail_ci_if_error: false
        
    - name: Run all example code
      run: |
        echo "Running all example code..."
        for example_dir in examples/*/; do
          if [ -f "${example_dir}main.go" ]; then
            echo "Running example: ${example_dir}"
            (cd "${example_dir}" && go run .)
          fi
        done 