name: Go Tests

on:
  push:
  pull_request:

jobs:
  unit-tests:
    name: 单元测试
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Go环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
        check-latest: true

    - name: 下载依赖
      run: go mod download

    - name: 执行单元测试
      run: go test -v ./...

    - name: 生成测试覆盖率报告
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: 上传覆盖率报告
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.txt
        fail_ci_if_error: false

  examples:
    name: 示例代码测试
    runs-on: ubuntu-latest
    needs: unit-tests # 确保单元测试通过后再运行示例
    steps:
    - name: 检出代码
      uses: actions/checkout@v3

    - name: 设置Go环境
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
        check-latest: true

    - name: 下载依赖
      run: go mod download
        
    - name: 执行所有示例代码
      run: |
        echo "开始执行所有示例代码..."
        for example_dir in examples/*/; do
          if [ -f "${example_dir}main.go" ]; then
            echo "执行示例: ${example_dir}"
            (cd "${example_dir}" && go run .)
          fi
        done 